name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image in /frontend
      run: docker build ./frontend --file ./frontend/Dockerfile --tag frontend-image:$(date +%s)
