name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-frontend:
    needs: build-backend
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Build the frontend Docker image
        run: docker build ./frontend --file ./frontend/Dockerfile --tag frontend-image:$(date +%s)

  build-backend:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Build the backend Docker image
        run: docker build ./mcq-sample-collect --file ./mcq-sample-collect/Dockerfile --tag backend-image:$(date +%s)
