name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Install dependencies
      run: |
          python -m venv .venv  # Create a virtual environment
          source .venv/bin/activate  # Activate the virtual environment
          python -m pip install --upgrade pip
          pip install sphinx
          pip install furo
          find . -name "requirements.txt" -execdir pip install -r requirements.txt \;
  
    - name: Install NLTK punkt (only needed for parse.py)
      run: |
            source .venv/bin/activate
            python -c "import nltk; nltk.download('punkt'); nltk.download('punkt_tab')"

    - name: Build HTML
      run: |
          source .venv/bin/activate  # Reactivate venv
          sphinx-build -b html sphinx/source sphinx/build/html/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: sphinx/build/html/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: sphinx/build/html
